### ISSUE TITLE
Expand Documentation about Node Ownership/Transfer

### ISSUE THREAD

**Issue by Deltt** [GD-Sync/GD-Sync#13]
I couldn't find information about how node ownership is being processed on a technical level, for example some very useful information about it would be:

- What does owner id -1 imply? (Since its the default, one would assume its the host, but why is it -1 by default? Are there any further implications to this?

- I assume transferring ownership is handled in an rpc-like manner, could that potentially lead to issue when 2 different peers have different ownership information of the same objects? Is it possible for this to happen or are there correctional mechanisms to prevent that? Or is there no such thing as cached local ownership information?

- Is ownership being set locally and then shared to other peers, or will the local ownership only change when other peers received that information?

- Is ownership safe to be used as an identifier which peer currently has "control" over an object, in cases where objects can be interacted with by only one peer at a time?

**Comment by ThomasUijlen** [comment]
We will make sure to adjust the documentation to clarify these points.

For now, here are the answers to your questions:

- ID -1 means that the Node does not have an owner. Any ID >= 0 indicates the Node has an owner.

- When setting/transfering ownership there is indeed a slight delay until all clients are notified of the new owner. One way to mitigate this is to do ownership checks on the host. Lets say player1 and player2 want to grab in item at roughly the same time; player1 checks with the host if the object has an owner or not, if not the host assigns player1 as the owner and sends a message back to indicate the grab was successful. The grab attempt from player2 is now discarded when it arrives at the host, since the item now already has an owner.

- Ownership is first set locally and then broadcasted to all other clients.

- Ownership is not 100% safe as there is no way to ensure that everyone has the same ownership information. The example of grabbing an object I gave fixes this.

**Comment by Deltt** [comment]
Thanks for the quick answer!

Does node ownership interact in a special way with rigidbodies? Am I right to assume that a rigidbody with -1 as owner and property synchronizers will just ignore/not receive any data and will be calculated locally?

**Comment by ThomasUijlen** [comment]
Node ownership does not do anything by itself. It is just a tool to help developers implement authoritative logic. If you want to synchronize Rigidbodies and for example allow someone to pick them up, these should be the steps:

- Add 2 PropertySynchronizers as children. Make sure to sync the global_position and global_basis so that position and rotation are synchronized.

- Enable interpolation for the synchronizers. We recommend keeping the interpolation speed the same as the refresh rate. If synced Rigidbodies lag behind on clients, try increasing the interpolation speed. Interpolation causes a slight delay as it smooths out the motions. The higher the refresh rate and interpolation speed, the less they will lag behind at the cost of more data usage.

- Set the Process of the PropertySynchronizer to Physics Process.

- On all clients except the host, make sure to enable “freeze” on the Rigidbody. This way the body is only simulated on the host, while other clients receive their positioning from the PropertySynchronizers.

- Set the PropertySynchronizers broadcast mode to either “When Host and no owner, or owner”. With this mode, if the Rigidbody has no owner it will automatically broadcast on the host. If for example, a player picks up the Rigidbody, you can use GDSync.set_gdsync_owner() to make them the owner of the Rigidbody. Now the host no longer broadcasts, but the client that is holding the Rigidbody does. Once you unassign the owner, the broadcasting switches back to the host.

- Make sure to update the Rigidbody freeze mode accordingly. You should only unfreeze it on the owner/host depending on if the object is being held or not. You can easily detect ownership changes with GDSync.connect_gdsync_owner_changed().

**Comment by ThomasUijlen** [comment]
The [node ownership documentation](https://www.gd-sync.com/documentation#nodeownership) has been expanded with extra details and more example code. Please let me know if the new version is clear enough or if it requires further improvements.

**Comment by Deltt** [comment]
The expanded documentation is much clearer, thank you.

Another thing I think would be valuable to know would be which methods actually execute network operations. For the longest time I was under the assumption GDSync.GetOwner() and  GDSync.IsOwner() would retrieve that info over the network from the session host, therefore I was hesitant to continuously poll it in condition checks to safe on bandwith. Going by your explanation above, that is not the case, and can potential confuse new users.

**Comment by ThomasUijlen** [comment]
I've reworded the last paragraph to state that Node ownership is stored locally per client. Closing this issue.
