### ISSUE TITLE
[improvement]

### ISSUE THREAD

**Issue by ianmckenna87** [GD-Sync/GD-Sync#17]
add descriptions to classes and functions (and as a bonus: in-editor documentation)

**Comment by ThomasUijlen** [comment]
Hi there!

Please check out [this part](https://www.gd-sync.com/documentation#gettingstarted-inenginedocumentation) of our documentation. All functions and signals in the GDSync singleton have documentation. This also includes the PropertySynchronizer and NodeInstantiator.

Due to a Godot bug, you need to edit those scripts in any way (just add an extra enter) and save them. Once you have done that the descriptions and documentation appear.

**Comment by ianmckenna87** [comment]
> Hi there!
> 
> Please check out [this part](https://www.gd-sync.com/documentation#gettingstarted-inenginedocumentation) of our documentation. All functions and signals in the GDSync singleton have documentation. This also includes the PropertySynchronizer and NodeInstantiator.
> 
> Due to a Godot bug, you need to edit those scripts in any way (just add an extra enter) and save them. Once you have done that the descriptions and documentation appear.

Thanks. i tried editing all the scripts but the only one that did the trick was GD-Sync.gd, after resaving that one, I am now able to view docs and see in editor descriptions of classess and properties
