### ISSUE TITLE
Reconnect issue

### ISSUE THREAD

**Issue by SadO-On** [GD-Sync/GD-Sync#2]
Firstly, I'd like to express my gratitude for the incredible service you've provided. Currently, I'm encountering a challenge in my game. I'm the developer of a mobile game called [Flag Hero](https://apps.apple.com/sa/app/flag-hero/id6482854375), available on the App Store. The issue arises when attempting to reconnect users.

The problem occurs within a multiplayer mobile game scenario, where a player shares a room ID with a friend to join a lobby and commence gameplay. Specifically, the issue arises when a player put the game in the background to share the code and then returns to the game, resulting in a lost connection. 

Attempts to address this problem involved invoking `GDSync.start_multiplayer()` upon detecting a disconnection, yet this approach failed because the expected signal connected never received Consequently, it remains unclear whether this is due to a bug or if there's a more effective method for implementing a retry connection feature.

Additionally, an observation was made that `GDSync.is_active()` erroneously returns true upon receiving the disconnection signal.

Please tell me If you want me to share a specific code

**Comment by ThomasUijlen** [comment]
Thank you for opening up an issue. We will look into the bug you mentioned as soon as possible!

While we investigate the issue, there might be a temporary solution. Could you try calling `GDSync.stop_multiplayer()`, before calling `GDSync.start_multiplayer()` when attempting to reconnect? This should fully clear the old connection.

**Comment by SadO-On** [comment]
I attempted to invoke `GDSync.start_multiplayer()` upon receiving the `disconnected` signal, encountering the same problem. Similarly, preceding it with `GDSync.stop_multiplayer()` yielded identical outcomes. Upon checking `is_active` and` GDSync.get_client_id()`, all returned values. My suspicion is that the disconnect signal is being emitted before the connection is properly cleaned up. 

BUT I discovered a workaround: introducing a delay before invoking `GDSync.start_multiplayer()` and It worked I was able to reconnect the player This's what I did
```gdscript
func _ready():
	super()
	GDSync.disconnected.connect(try_to_reconnect)
	GDSync.connected.connect(connect_again)
	GDSync.connection_failed.connect(connect_failed)



func try_to_reconnect():
	if lock == true:
		await get_tree().create_timer(1).timeout
		GDSync.start_multiplayer()
	else:
		lock = true
		print("try_to_reconnect")
		GDSync.stop_multiplayer()

func connect_again():
	print("Connected")
	
func connect_failed():
	print("failed")	
```

**Comment by SadO-On** [comment]
Additionally, If you can provide a function to check the connection health. It would be useful to use it whenever the application returned from the background and be visible again.

**Comment by ThomasUijlen** [comment]
Hi there! Thank you for providing the extra info.

I can confirm your suspicions were indeed correct. The disconnect signal was being called too early, before the connection was fully cleaned up. The plugin blocks `GDSync.start_multiplayer()` if a connection is still present, which is why instantly reconnecting didn't work. The old connection was still present when the disconnect signal was emitted.

I have pushed a possible fix. It includes two changes:
1. The `disconnected` signal is now emitted **after** the connection is fully cleaned up. This should allow you to instantly call `GDSync.start_multiplayer()` after disconnecting.
2. The `disconnected` signal is now called instantly after returning to the game. Before the socket waited for a timeout to happen, which introduced extra delay before the connection was terminated. This process is now instant, which should allow you to reconnect a bit quicker in case of a disconnect.

You can download the newest version right here from the repository. Please let me know if the issue has been resolved or not!

**Comment by ThomasUijlen** [comment]
> Additionally, If you can provide a function to check the connection health

`GDSync.is_active()` is the function to use to check if the connection is still active or not. With the new changes it should now function as expected. However, I would still recommend only using the `disconnected` and `connected` signals.

**Comment by SadO-On** [comment]
Thanks I'll check it and get back to you.

**Comment by ThomasUijlen** [comment]
Closing this issue. If the issue still persists please reply on this thread or open a new one.
